// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmcojwDNcWWWeVnf4um45MoENQ0DIUeRQ',
    appId: '1:217693925946:web:f24c3fab7e0a30539cfb03',
    messagingSenderId: '217693925946',
    projectId: 'flutter-app-aa5b5',
    authDomain: 'flutter-app-aa5b5.firebaseapp.com',
    storageBucket: 'flutter-app-aa5b5.appspot.com',
    measurementId: 'G-EQYTK61ZR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNycHzkDjrnR6Z4zc7QQb2P-17_ggQDpI',
    appId: '1:217693925946:android:d300ea1848d9e0329cfb03',
    messagingSenderId: '217693925946',
    projectId: 'flutter-app-aa5b5',
    storageBucket: 'flutter-app-aa5b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLf3SkmmPXvPc9R-7F0YNuPySEWW3krso',
    appId: '1:217693925946:ios:0cda066825f1535c9cfb03',
    messagingSenderId: '217693925946',
    projectId: 'flutter-app-aa5b5',
    storageBucket: 'flutter-app-aa5b5.appspot.com',
    iosClientId: '217693925946-fedt54gvp4nst5ntpk9dj3ifp0j5rb08.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
